### ISSUE TITLE
Create / Download Canonical protein fasta file from ENSEMBL 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/py-pgatk#1]
- [ ] **Input**: (specific taxonomy - species - to be download) or all the species from ENSEMBL. A folder where the files will be download. 

- [ ] **Output**: The canonical FASTA file for the specific taxonomy (species)

**Comment by ypriverol** [comment]
We should be able to download cds for ensembl ftp://ftp.ensembl.org/pub/release-96/fasta/homo_sapiens/cds/

**Comment by ypriverol** [comment]
The tool will need to download in addition ncRNA

**Comment by ypriverol** [comment]
The current version contains downloads for cds and ncRNAs as agreed.

**Comment by husensofteng** [comment]
and vcfs

**Comment by husensofteng** [comment]
done
