### ISSUE TITLE
overlap between config parameters in cgenomes between cosmic and cbioportal downloaders

### ISSUE THREAD

**Issue by husensofteng** [bigbio/py-pgatk#17]
refactoring is need for removing '`clinical_sample_file`' from `cosmic_config.yaml` without breaking `cosmic_to_proteindb` in `cgenomes_proteindb.py`:
https://github.com/bigbio/py-pgatk/blob/067aa7c90e8706559cc8cf841262920c3221f45c/pypgatk/cgenomes/cgenomes_proteindb.py#L18

to be removed:
https://github.com/bigbio/py-pgatk/blob/067aa7c90e8706559cc8cf841262920c3221f45c/pypgatk/config/cosmic_config.yaml#L19

**Comment by ypriverol** [comment]
@husensofteng I have managed to move the project into Travis. Some minor changes has been done in the string format. 

Can you let me know, what is this error you are mentioning here?

**Comment by ypriverol** [comment]
@husensofteng error in the test https://github.com/bigbio/py-pgatk/blob/364fdcdfe1c58a68370e431995c3b7a2cd963d8f/pypgatk/tests/pypgatk_tests.py#L155

**Comment by husensofteng** [comment]
the error is fixed. the issue was related to logger variables. they had to be moved into the class: [here](https://github.com/bigbio/py-pgatk/commit/cf4ce653f90e46c80cb15cf2ca0a0c0cee66adcb#diff-354d9bc8897ef92b30887ed86c0bb1e0R30)

**Comment by husensofteng** [comment]
@ypriverol if we could check we will close the issue.
