### ISSUE TITLE
Major review to the code

### ISSUE THREAD

**Issue by ypriverol** [bigbio/py-pgatk#8]
@yafeng : 

I have made all the changes requested, the current version of the library contains two new commands: 

- cosmic-to-proteindb 
- cbioportal-to-proteindb 

I have removed the scripts from the DB folder. The last thing is missing is for you to review some of the code comments of variables that are not use: 

https://github.com/bigbio/py-pgatk/blob/master/cgenomes/cgenomes_proteindb.py#L95

When you finish let me know !!!

**Comment by yafeng** [comment]
Done! commits pushed.

**Comment by husensofteng** [comment]
refactoring is need for removing '`clinical_sample_file`' from `cosmic_config.yaml` without breaking `cosmic_to_proteindb` in `cgenomes_proteindb.py`
